"""Add customer-account relation

Revision ID: 3b5eaefddd86
Revises: bdc210dd3ae9
Create Date: 2025-05-26 15:40:10.117484

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3b5eaefddd86'
down_revision: Union[str, None] = 'bdc210dd3ae9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('ssn', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ssn')
    )
    op.create_table('accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number', sa.String(), nullable=False),
    sa.Column('balance', sa.Numeric(), nullable=False),
    sa.Column('credit', sa.Numeric(), nullable=True),
    sa.Column('interest', sa.Numeric(), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('customer')
    op.drop_table('account')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('number', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('balance', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('credit', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('interest', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('currency', sa.VARCHAR(length=3), autoincrement=False, nullable=False),
    sa.Column('customer_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], name=op.f('account_customer_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('account_pkey'))
    )
    op.create_table('customer',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('ssn', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('customer_pkey')),
    sa.UniqueConstraint('ssn', name=op.f('customer_ssn_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.drop_table('accounts')
    op.drop_table('customers')
    # ### end Alembic commands ###
