"""Initial schema

Revision ID: aded31140cf4
Revises: 3b5eaefddd86
Create Date: 2025-05-27 08:52:02.659797

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aded31140cf4'
down_revision: Union[str, None] = '3b5eaefddd86'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('ssn', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ssn')
    )
    op.create_table('accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number', sa.String(), nullable=False),
    sa.Column('balance', sa.Numeric(), nullable=False),
    sa.Column('credit', sa.Numeric(), nullable=True),
    sa.Column('interest', sa.Numeric(), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('Transaction_Cleaned')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Transaction_Cleaned',
    sa.Column('transaction_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('timestamp', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('currency', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('sender_account', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('receiver_account', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('sender_country', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('sender_municipality', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('receiver_country', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('receiver_municipality', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('transaction_type', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('timestamp_original', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('timestamp_cleaned', sa.TEXT(), autoincrement=False, nullable=True)
    )
    op.drop_table('accounts')
    op.drop_table('customers')
    # ### end Alembic commands ###
