"""Initial schema

Revision ID: bdc210dd3ae9
Revises: 2d692627da72
Create Date: 2025-05-26 15:35:33.152629

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bdc210dd3ae9'
down_revision: Union[str, None] = '2d692627da72'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Transaction_Cleaned')
    op.drop_constraint(op.f('account_balance_key'), 'account', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('account_balance_key'), 'account', ['balance'], postgresql_nulls_not_distinct=False)
    op.create_table('Transaction_Cleaned',
    sa.Column('transaction_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('timestamp', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('currency', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('sender_account', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('receiver_account', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('sender_country', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('sender_municipality', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('receiver_country', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('receiver_municipality', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('transaction_type', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('timestamp_original', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('timestamp_cleaned', sa.TEXT(), autoincrement=False, nullable=True)
    )
    # ### end Alembic commands ###
